# Generated by Django 6.0.5 on 2026-05-27 04:40

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CUSTOMER', 'Customer'), ('BUSINESS_OWNER', 'Business_Owner'), ('STAFF', 'Staff')], default='CUSTOMER', max_length=32)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('GOOGLE', 'Google')], max_length=32)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_auth_methods',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthmethod',
            index=models.Index(fields=['provider', 'provider_user_id'], name='user_auth_m_provide_69ba76_idx'),
        ),
        migrations.AddIndex(
            model_name='userauthmethod',
            index=models.Index(fields=['user'], name='user_auth_m_user_id_ffd5d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userauthmethod',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
