# Generated by Django 6.0.2 on 2026-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CUSTOMER', 'Customer'), ('BUSINESS_OWNER', 'Business_Owner'), ('RECEPTIONIST', 'Receptionist'), ('HOUSEKEEPING', 'Housekeeping'), ('SERVICE', 'Service'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='CUSTOMER', max_length=32),
        ),
    ]
