# Generated by Django 6.0.2 on 2026-05-30 12:00

from django.db import migrations

from core.migration_utils import rename_index_if_exists

NOTIFICATION_INDEX_RENAMES = [
    ("user_notifications", "user_notifi_user_id_8a1b0d_idx", "user_notifi_user_id_c4416a_idx"),
    ("user_notifications", "user_notifi_user_id_2c4e1a_idx", "user_notifi_user_id_a42415_idx"),
]


def sync_notification_index_renames(apps, schema_editor):
    for table_name, old_name, new_name in NOTIFICATION_INDEX_RENAMES:
        rename_index_if_exists(schema_editor, table_name, old_name, new_name)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('accounts', '0006_user_notification'),
    ]

    operations = [
        migrations.RunPython(sync_notification_index_renames, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='usernotification',
                    new_name='user_notifi_user_id_c4416a_idx',
                    old_name='user_notifi_user_id_8a1b0d_idx',
                ),
                migrations.RenameIndex(
                    model_name='usernotification',
                    new_name='user_notifi_user_id_a42415_idx',
                    old_name='user_notifi_user_id_2c4e1a_idx',
                ),
            ],
        ),
    ]
