# Generated by Django 6.0.2 on 2026-05-27 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_code', models.CharField(max_length=64, unique=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=32)),
                ('walk_in', models.BooleanField(default=False)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('expected_check_out_at', models.DateTimeField(blank=True, null=True)),
                ('hotel_name', models.CharField(blank=True, default='', max_length=255)),
                ('hotel_address', models.TextField(blank=True, default='')),
                ('room_type', models.CharField(blank=True, default='', max_length=255)),
                ('original_room_number', models.CharField(blank=True, default='', max_length=32)),
                ('room_change_note', models.TextField(blank=True, default='')),
                ('hourly_rate', models.IntegerField(default=0)),
                ('base_price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='businesses.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.room')),
                ('room_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.roomcategory')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingExtraService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_key', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_extra_services',
            },
        ),
    ]
