# Generated by Django 6.0.5 on 2026-05-28 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking_sequences',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_number', models.PositiveBigIntegerField(db_index=True, editable=False, unique=True)),
                ('booking_id', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('hotel_name', models.CharField(blank=True, default='', max_length=255)),
                ('room_name', models.CharField(blank=True, default='', max_length=255)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_id'], name='bookings_bo_booking_cf80ec_idx'), models.Index(fields=['booking_number'], name='bookings_bo_booking_a57f20_idx'), models.Index(fields=['customer'], name='bookings_bo_custome_90d1e0_idx'), models.Index(fields=['status'], name='bookings_bo_status_fdeadc_idx')],
            },
        ),
    ]
