# Generated by Django 6.0.2 on 2026-05-30 11:10



import cloudinary.models

import django.db.models.deletion

from django.conf import settings

from django.db import migrations, models



from core.migration_utils import (

    add_db_index_if_missing,

    add_model_fields_if_missing,

    add_unique_constraint_if_missing,

    existing_columns,

    drop_foreign_key_column_if_present,

    rename_index_if_exists,

)



REVIEW_INDEX_RENAMES = [

    ("review_forum_posts", "review_forum_scope_k_7c5aa9_idx", "review_foru_scope_k_492718_idx"),

    ("review_forum_posts", "review_forum_hotel_n_1b89e0_idx", "review_foru_hotel_n_2fe70e_idx"),

]





def dedupe_booking_line_display_codes(apps, schema_editor):

    BookingLineItem = apps.get_model("bookings", "BookingLineItem")

    seen: set[tuple] = set()

    for line in BookingLineItem.objects.order_by("booking_id", "created_at").iterator():

        key = (line.booking_id, line.display_code or "")

        if not line.display_code or key not in seen:

            seen.add(key)

            continue

        line.display_code = f"{line.display_code}-{str(line.id).replace('-', '')[:6]}"

        line.save(update_fields=["display_code"])





def sync_review_forum_post_schema(apps, schema_editor):

    ReviewForumPost = apps.get_model("bookings", "ReviewForumPost")

    Branch = apps.get_model("businesses", "Branch")

    table = ReviewForumPost._meta.db_table

    present = existing_columns(schema_editor, table)



    if "branch_id" not in present:

        field = models.ForeignKey(

            Branch,

            null=True,

            blank=True,

            on_delete=django.db.models.deletion.SET_NULL,

            related_name="locket_posts",

            name="branch",

        )

        field.set_attributes_from_name("branch")

        schema_editor.add_field(ReviewForumPost, field)



    if "image" not in present:

        field = cloudinary.models.CloudinaryField("image", blank=True, null=True, name="image")

        field.set_attributes_from_name("image")

        schema_editor.add_field(ReviewForumPost, field)



    present = existing_columns(schema_editor, table)

    if "booking_ref_id" not in present:

        Booking = apps.get_model("bookings", "Booking")

        field = models.ForeignKey(

            Booking,

            null=True,

            blank=True,

            on_delete=django.db.models.deletion.SET_NULL,

            related_name="reviews",

            name="booking_ref",

        )

        field.set_attributes_from_name("booking_ref")

        schema_editor.add_field(ReviewForumPost, field)

        present = existing_columns(schema_editor, table)



    if "booking_id" in present and "booking_ref_id" in present:

        with schema_editor.connection.cursor() as cursor:

            cursor.execute(

                f"UPDATE {schema_editor.quote_name(table)} "

                f"SET {schema_editor.quote_name('booking_ref_id')} = {schema_editor.quote_name('booking_id')} "

                f"WHERE {schema_editor.quote_name('booking_ref_id')} IS NULL "

                f"AND {schema_editor.quote_name('booking_id')} IS NOT NULL"

            )

        drop_foreign_key_column_if_present(schema_editor, table, "booking_id")

    elif "booking_id" in present:

        drop_foreign_key_column_if_present(schema_editor, table, "booking_id")





def sync_bookings_0007_database(apps, schema_editor):

    for table_name, old_name, new_name in REVIEW_INDEX_RENAMES:

        rename_index_if_exists(schema_editor, table_name, old_name, new_name)



    sync_review_forum_post_schema(apps, schema_editor)



    user_label, user_model_name = settings.AUTH_USER_MODEL.split(".")

    User = apps.get_model(user_label, user_model_name)

    BookingLineItem = apps.get_model("bookings", "BookingLineItem")

    add_model_fields_if_missing(

        schema_editor,

        BookingLineItem,

        [

            models.ForeignKey(

                User,

                blank=True,

                null=True,

                on_delete=django.db.models.deletion.SET_NULL,

                related_name="assigned_booking_line_items",

                name="assigned_to",

            ),

        ],

    )



    add_db_index_if_missing(

        schema_editor,

        "bookings",

        "booking_avail_status_idx",

        ["branch_id", "room_category_id", "status"],

    )

    add_db_index_if_missing(

        schema_editor,

        "bookings",

        "booking_avail_checkin_idx",

        ["branch_id", "room_category_id", "check_in_at"],

    )

    add_db_index_if_missing(

        schema_editor,

        "review_forum_posts",

        "review_foru_booking_fecd25_idx",

        ["booking_ref", "created_at"],

    )

    add_db_index_if_missing(

        schema_editor,

        "review_forum_posts",

        "review_foru_branch__0bf76c_idx",

        ["branch_id", "created_at"],

    )





def add_booking_line_constraint(apps, schema_editor):

    add_unique_constraint_if_missing(

        schema_editor,

        "booking_line_items",

        "uniq_booking_line_display_code",

        ["booking_id", "display_code"],

    )





class Migration(migrations.Migration):

    atomic = False



    dependencies = [

        ('bookings', '0006_bookinglineitem_display_code'),

        ('businesses', '0005_branch_themes_m2m'),

        ('rooms', '0007_roomtheme_catalog_fields'),

        ('service_orders', '0002_extraservice_icon'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]



    operations = [

        migrations.RunPython(sync_bookings_0007_database, migrations.RunPython.noop),

        migrations.AlterModelOptions(

            name='reviewforumpost',

            options={},

        ),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.RenameIndex(

                    model_name='reviewforumpost',

                    new_name='review_foru_scope_k_492718_idx',

                    old_name='review_forum_scope_k_7c5aa9_idx',

                ),

                migrations.RenameIndex(

                    model_name='reviewforumpost',

                    new_name='review_foru_hotel_n_2fe70e_idx',

                    old_name='review_forum_hotel_n_1b89e0_idx',

                ),

                migrations.RemoveField(

                    model_name='reviewforumpost',

                    name='booking_id',

                ),

                migrations.AddField(

                    model_name='reviewforumpost',

                    name='branch',

                    field=models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.SET_NULL,

                        related_name='locket_posts',

                        to='businesses.branch',

                    ),

                ),

                migrations.AddField(

                    model_name='reviewforumpost',

                    name='image',

                    field=cloudinary.models.CloudinaryField(

                        blank=True, max_length=255, null=True, verbose_name='image'

                    ),

                ),

            ],

        ),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.AddField(

                    model_name='bookinglineitem',

                    name='assigned_to',

                    field=models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.SET_NULL,

                        related_name='assigned_booking_line_items',

                        to=settings.AUTH_USER_MODEL,

                    ),

                ),

            ],

        ),

        migrations.AlterField(

            model_name='booking',

            name='hotel_address',

            field=models.TextField(blank=True, default='', help_text='Snapshot of branch address at booking time.'),

        ),

        migrations.AlterField(

            model_name='booking',

            name='hotel_name',

            field=models.CharField(blank=True, default='', help_text='Snapshot of branch name at booking time.', max_length=255),

        ),

        migrations.AlterField(

            model_name='booking',

            name='room_type',

            field=models.CharField(blank=True, default='', help_text='Snapshot of room category name at booking time.', max_length=255),

        ),

        migrations.AlterField(

            model_name='booking',

            name='status',

            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('CANCELLED', 'Cancelled'), ('CANCELLED_NO_SHOW', 'Cancelled no-show')], db_index=True, default='PENDING', max_length=32),

        ),

        migrations.AlterField(

            model_name='bookinglineitem',

            name='assigned_staff',

            field=models.CharField(blank=True, default='', help_text='Display name fallback when staff user is not linked.', max_length=255),

        ),

        migrations.AlterField(

            model_name='bookinglineitem',

            name='source',

            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('RECEPTION', 'Reception')], default='CUSTOMER', max_length=32),

        ),

        migrations.AlterField(

            model_name='bookinglineitem',

            name='status',

            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32),

        ),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.AddIndex(

                    model_name='booking',

                    index=models.Index(fields=['branch', 'room_category', 'status'], name='booking_avail_status_idx'),

                ),

                migrations.AddIndex(

                    model_name='booking',

                    index=models.Index(fields=['branch', 'room_category', 'check_in_at'], name='booking_avail_checkin_idx'),

                ),

                migrations.AddIndex(

                    model_name='reviewforumpost',

                    index=models.Index(fields=['booking_ref', 'created_at'], name='review_foru_booking_fecd25_idx'),

                ),

                migrations.AddIndex(

                    model_name='reviewforumpost',

                    index=models.Index(fields=['branch', 'created_at'], name='review_foru_branch__0bf76c_idx'),

                ),

            ],

        ),

        migrations.RunPython(dedupe_booking_line_display_codes, migrations.RunPython.noop),

        migrations.RunPython(add_booking_line_constraint, migrations.RunPython.noop),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.AddConstraint(

                    model_name='bookinglineitem',

                    constraint=models.UniqueConstraint(fields=('booking', 'display_code'), name='uniq_booking_line_display_code'),

                ),

            ],

        ),

    ]


