# Generated by Django 6.0.2 on 2026-05-27 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'business_departments',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, max_length=1000, null=True)),
                ('lodging_type', models.CharField(blank=True, default='', max_length=64)),
                ('business_type', models.CharField(blank=True, default='', max_length=64)),
                ('scale', models.CharField(blank=True, default='', max_length=64)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_code', models.CharField(blank=True, default='', max_length=64)),
                ('legal_representative', models.CharField(blank=True, default='', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=64)),
                ('headquarters_address', models.TextField(blank=True, default='')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_companies',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('lodging_type', models.CharField(blank=True, default='', max_length=64)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('guest_segments', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('bank_name', models.CharField(blank=True, default='', max_length=128)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='businesses.company')),
            ],
            options={
                'db_table': 'business_branches',
            },
        ),
    ]
