# Generated by Django 6.0.5 on 2026-05-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hotel',
            new_name='business_ho_categor_f3b828_idx',
            old_name='business_ho_categor_8f954d_idx',
        ),
        migrations.RenameIndex(
            model_name='hotel',
            new_name='business_ho_city_1d94d1_idx',
            old_name='business_ho_city_8ea2cf_idx',
        ),
    ]
