# Generated by Django 6.0.2 on 2026-05-27 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(blank=True, default='', max_length=32)),
                ('issue_type', models.CharField(blank=True, default='Maintenance', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='businesses.branch')),
            ],
            options={
                'db_table': 'maintenance_issues',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('base_price', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('room_amenities', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='businesses.branch')),
            ],
            options={
                'db_table': 'room_categories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=32)),
                ('floor', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(db_index=True, default='AVAILABLE', max_length=32)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='businesses.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomcategory')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
