# Generated by Django 6.0.2 on 2026-05-30 11:10



import django.db.models.deletion

import uuid

from django.conf import settings

from django.db import migrations, models

from django.db.models import Count



from core.migration_utils import (

    add_db_index_if_missing,

    add_model_fields_if_missing,

    add_unique_constraint_if_missing,

    remove_column_if_present,

    rename_index_if_exists,

)



INDEX_RENAMES = [

    ("branch_themes", "branch_themes_branch_theme_idx", "branch_them_branch__54cc9e_idx"),

    ("branch_themes", "branch_themes_theme_idx", "branch_them_theme_i_5eecb8_idx"),

    ("housekeeping_tasks", "housekeepin_branch__c9b2d9_idx", "housekeepin_branch__62d04c_idx"),

    ("housekeeping_tasks", "housekeepin_room__caef1d_idx", "housekeepin_room_id_a30c3c_idx"),

    ("room_themes", "room_themes_name_idx", "room_themes_name_78a192_idx"),

    ("room_themes", "room_themes_active_sort_idx", "room_themes_is_acti_4db63b_idx"),

    ("room_theme_links", "room_theme_links_room_theme_idx", "room_theme__room_id_d3933f_idx"),

    ("room_theme_links", "room_theme_links_theme_idx", "room_theme__theme_i_f5159b_idx"),

]





def dedupe_room_numbers(apps, schema_editor):

    Room = apps.get_model("rooms", "Room")

    dupes = (

        Room.objects.values("branch_id", "room_number")

        .annotate(total=Count("id"))

        .filter(total__gt=1)

    )

    for row in dupes:

        qs = Room.objects.filter(branch_id=row["branch_id"], room_number=row["room_number"]).order_by(

            "created_at", "id"

        )

        for room in qs[1:]:

            room.room_number = f"{room.room_number}-{str(room.id).replace('-', '')[:6]}"

            room.save(update_fields=["room_number"])





def dedupe_room_category_names(apps, schema_editor):

    RoomCategory = apps.get_model("rooms", "RoomCategory")

    dupes = (

        RoomCategory.objects.values("branch_id", "name")

        .annotate(total=Count("id"))

        .filter(total__gt=1)

    )

    for row in dupes:

        qs = RoomCategory.objects.filter(branch_id=row["branch_id"], name=row["name"]).order_by(

            "created_at", "id"

        )

        for category in qs[1:]:

            category.name = f"{category.name}-{str(category.id).replace('-', '')[:6]}"

            category.save(update_fields=["name"])





def ensure_hardening_columns(apps, schema_editor):

    """Add columns/indexes that may be missing when earlier migrations were partially applied."""

    HousekeepingTask = apps.get_model("rooms", "HousekeepingTask")

    MaintenanceIssue = apps.get_model("rooms", "MaintenanceIssue")

    user_label, user_model_name = settings.AUTH_USER_MODEL.split(".")

    User = apps.get_model(user_label, user_model_name)



    add_model_fields_if_missing(

        schema_editor,

        HousekeepingTask,

        [

            models.ForeignKey(

                User,

                blank=True,

                null=True,

                on_delete=django.db.models.deletion.SET_NULL,

                related_name="housekeeping_tasks",

                name="assigned_to",

            ),

        ],

    )

    Room = apps.get_model("rooms", "Room")

    add_model_fields_if_missing(

        schema_editor,

        MaintenanceIssue,

        [

            models.ForeignKey(

                Room,

                blank=True,

                null=True,

                on_delete=django.db.models.deletion.CASCADE,

                related_name="maintenance_issues",

                name="room",

            ),

        ],

    )

    add_db_index_if_missing(

        schema_editor,

        "housekeeping_tasks",

        "housekeepin_assigne_c83cee_idx",

        ["assigned_to_id", "status"],

    )





def link_maintenance_rooms(apps, schema_editor):

    MaintenanceIssue = apps.get_model("rooms", "MaintenanceIssue")

    Room = apps.get_model("rooms", "Room")

    table = MaintenanceIssue._meta.db_table

    present = set()

    with schema_editor.connection.cursor() as cursor:

        for col in schema_editor.connection.introspection.get_table_description(cursor, table):

            present.add(col.name)



    if "room_number" in present:

        for issue in MaintenanceIssue.objects.all().iterator():

            room_number = getattr(issue, "room_number", "") or ""

            if not room_number or issue.room_id:

                continue

            room = Room.objects.filter(branch_id=issue.branch_id, room_number=room_number).first()

            if room:

                issue.room_id = room.id

                issue.save(update_fields=["room_id"])

        remove_column_if_present(schema_editor, table, "room_number")





def sync_0008_database(apps, schema_editor):

    ensure_hardening_columns(apps, schema_editor)

    for table_name, old_name, new_name in INDEX_RENAMES:

        rename_index_if_exists(schema_editor, table_name, old_name, new_name)

    link_maintenance_rooms(apps, schema_editor)

    add_db_index_if_missing(

        schema_editor,

        "maintenance_issues",

        "maintenance_branch__c7d3d5_idx",

        ["branch_id", "is_resolved"],

    )

    add_db_index_if_missing(

        schema_editor,

        "rooms",

        "rooms_branch__981868_idx",

        ["branch_id", "category_id", "status"],

    )





def add_hardening_constraints(apps, schema_editor):

    add_unique_constraint_if_missing(

        schema_editor,

        "rooms",

        "uniq_room_branch_number",

        ["branch_id", "room_number"],

    )

    add_unique_constraint_if_missing(

        schema_editor,

        "room_categories",

        "uniq_room_category_branch_name",

        ["branch_id", "name"],

    )





class Migration(migrations.Migration):
    atomic = False

    dependencies = [

        ('businesses', '0005_branch_themes_m2m'),

        ('rooms', '0007_roomtheme_catalog_fields'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]



    operations = [

        migrations.RunPython(sync_0008_database, migrations.RunPython.noop),

        migrations.AlterModelOptions(

            name='roomtheme',

            options={'ordering': ['sort_order', 'name']},

        ),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.RenameIndex(

                    model_name='branchtheme',

                    new_name='branch_them_branch__54cc9e_idx',

                    old_name='branch_themes_branch_theme_idx',

                ),

                migrations.RenameIndex(

                    model_name='branchtheme',

                    new_name='branch_them_theme_i_5eecb8_idx',

                    old_name='branch_themes_theme_idx',

                ),

                migrations.RenameIndex(

                    model_name='housekeepingtask',

                    new_name='housekeepin_branch__62d04c_idx',

                    old_name='housekeepin_branch__c9b2d9_idx',

                ),

                migrations.RenameIndex(

                    model_name='housekeepingtask',

                    new_name='housekeepin_room_id_a30c3c_idx',

                    old_name='housekeepin_room__caef1d_idx',

                ),

                migrations.RenameIndex(

                    model_name='roomtheme',

                    new_name='room_themes_name_78a192_idx',

                    old_name='room_themes_name_idx',

                ),

                migrations.RenameIndex(

                    model_name='roomtheme',

                    new_name='room_themes_is_acti_4db63b_idx',

                    old_name='room_themes_active_sort_idx',

                ),

                migrations.RenameIndex(

                    model_name='roomthemelink',

                    new_name='room_theme__room_id_d3933f_idx',

                    old_name='room_theme_links_room_theme_idx',

                ),

                migrations.RenameIndex(

                    model_name='roomthemelink',

                    new_name='room_theme__theme_i_f5159b_idx',

                    old_name='room_theme_links_theme_idx',

                ),

            ],

        ),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.AddField(

                    model_name='maintenanceissue',

                    name='room',

                    field=models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.CASCADE,

                        related_name='maintenance_issues',

                        to='rooms.room',

                    ),

                ),

                migrations.RemoveField(

                    model_name='maintenanceissue',

                    name='room_number',

                ),

                migrations.AddField(

                    model_name='housekeepingtask',

                    name='assigned_to',

                    field=models.ForeignKey(

                        blank=True,

                        null=True,

                        on_delete=django.db.models.deletion.SET_NULL,

                        related_name='housekeeping_tasks',

                        to=settings.AUTH_USER_MODEL,

                    ),

                ),

            ],

        ),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.RenameField(

                    model_name='roomcategory',

                    old_name='capacity',

                    new_name='max_guests',

                ),

                migrations.AlterField(

                    model_name='roomcategory',

                    name='max_guests',

                    field=models.IntegerField(

                        db_column='capacity',

                        default=1,

                        help_text='Maximum guest occupancy for this room category.',

                    ),

                ),

            ],

        ),

        migrations.AlterField(

            model_name='branchtheme',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='housekeepingtask',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='room',

            name='status',

            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_ORDER', 'Out of order')], db_index=True, default='AVAILABLE', max_length=32),

        ),

        migrations.AlterField(

            model_name='roomtheme',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='roomthemelink',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),

        ),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.AddIndex(

                    model_name='housekeepingtask',

                    index=models.Index(fields=['assigned_to', 'status'], name='housekeepin_assigne_c83cee_idx'),

                ),

                migrations.AddIndex(

                    model_name='maintenanceissue',

                    index=models.Index(fields=['branch', 'is_resolved'], name='maintenance_branch__c7d3d5_idx'),

                ),

                migrations.AddIndex(

                    model_name='room',

                    index=models.Index(fields=['branch', 'category', 'status'], name='rooms_branch__981868_idx'),

                ),

            ],

        ),

        migrations.RunPython(dedupe_room_numbers, migrations.RunPython.noop),

        migrations.RunPython(dedupe_room_category_names, migrations.RunPython.noop),

        migrations.RunPython(add_hardening_constraints, migrations.RunPython.noop),

        migrations.SeparateDatabaseAndState(

            database_operations=[],

            state_operations=[

                migrations.AddConstraint(

                    model_name='room',

                    constraint=models.UniqueConstraint(fields=('branch', 'room_number'), name='uniq_room_branch_number'),

                ),

                migrations.AddConstraint(

                    model_name='roomcategory',

                    constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_room_category_branch_name'),

                ),

            ],

        ),

    ]


