# Generated by Django 6.0.5 on 2026-05-28 08:46

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBookingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('booking_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('snapshot_type', models.CharField(choices=[('upcoming', 'Upcoming'), ('history', 'History'), ('payment', 'Payment')], db_index=True, max_length=16)),
                ('hotel_name', models.CharField(blank=True, default='', max_length=255)),
                ('room_name', models.CharField(blank=True, default='', max_length=255)),
                ('check_in_label', models.CharField(blank=True, default='', max_length=64)),
                ('check_out_label', models.CharField(blank=True, default='', max_length=64)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('action_label', models.CharField(blank=True, default='', max_length=64)),
                ('action_color', models.CharField(blank=True, default='', max_length=16)),
                ('payment_status', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('payment_method', models.CharField(blank=True, default='', max_length=32)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selected_services', models.JSONField(blank=True, null=True)),
                ('invoice_details', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='mobile-app', max_length=32)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_booking_snapshots',
                'indexes': [models.Index(fields=['customer', 'snapshot_type', 'created_at'], name='customer_bo_custome_17a558_idx'), models.Index(fields=['booking_code', 'snapshot_type'], name='customer_bo_booking_7a3194_idx'), models.Index(fields=['hotel_name', 'room_name'], name='customer_bo_hotel_n_6ade3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerHotelRating',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('booking_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(blank=True, default='', max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('source', models.CharField(blank=True, default='checkout', max_length=32)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_hotel_ratings',
                'indexes': [models.Index(fields=['customer', 'created_at'], name='customer_ho_custome_c6c0c1_idx'), models.Index(fields=['booking_code'], name='customer_ho_booking_7ba85a_idx'), models.Index(fields=['hotel_name', 'room_name', 'created_at'], name='customer_ho_hotel_n_a3de04_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('notification_type', models.CharField(blank=True, db_index=True, default='general', max_length=64)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_notifications',
                'indexes': [models.Index(fields=['customer', 'is_read', 'created_at'], name='customer_no_custome_57df0b_idx'), models.Index(fields=['notification_type', 'created_at'], name='customer_no_notific_237a06_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerWatchlistPost',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('booking_code', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('hotel_name', models.CharField(max_length=255)),
                ('room_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('posted_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('posted_by_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_watchlist_posts',
                'indexes': [models.Index(fields=['customer', 'created_at'], name='customer_wa_custome_c423e5_idx'), models.Index(fields=['booking_code'], name='customer_wa_booking_b4fdeb_idx'), models.Index(fields=['hotel_name', 'room_name'], name='customer_wa_hotel_n_c1f061_idx')],
            },
        ),
    ]
