# Generated by Django 6.0.2 on 2026-05-27 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='RESTAURANT', max_length=64)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='businesses.branch')),
            ],
            options={
                'db_table': 'extra_services',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='ROOM_SERVICE', max_length=64)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('room_number', models.CharField(blank=True, default='', max_length=32)),
                ('guest_name', models.CharField(blank=True, default='', max_length=255)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=64)),
                ('assigned_staff', models.CharField(blank=True, default='', max_length=255)),
                ('items', models.JSONField(blank=True, default=list)),
                ('amount', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='bookings.booking')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='businesses.branch')),
            ],
            options={
                'db_table': 'service_orders',
            },
        ),
    ]
