# Generated by Django 6.0.2 on 2026-05-30 11:10

from django.db import migrations, models
from django.db.models import Count

from core.migration_utils import (
    add_column_index_if_missing,
    add_model_fields_if_missing,
    add_unique_constraint_if_missing,
    create_model_if_missing,
)


def ensure_service_order_schema(apps, schema_editor):
    create_model_if_missing(apps, schema_editor, "service_orders", "ExtraService")
    create_model_if_missing(apps, schema_editor, "service_orders", "ServiceOrder")

    ExtraService = apps.get_model("service_orders", "ExtraService")
    add_model_fields_if_missing(
        schema_editor,
        ExtraService,
        [models.CharField(max_length=64, blank=True, default="sparkles-outline", name="icon")],
    )
    add_column_index_if_missing(schema_editor, "service_orders", "status")


def dedupe_extra_services(apps, schema_editor):
    ExtraService = apps.get_model("service_orders", "ExtraService")
    dupes = (
        ExtraService.objects.values("branch_id", "name")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for row in dupes:
        qs = ExtraService.objects.filter(branch_id=row["branch_id"], name=row["name"]).order_by(
            "created_at", "id"
        )
        for extra in qs[1:]:
            extra.name = f"{extra.name}-{str(extra.id).replace('-', '')[:6]}"
            extra.save(update_fields=["name"])


def add_extra_service_constraint(apps, schema_editor):
    add_unique_constraint_if_missing(
        schema_editor,
        "extra_services",
        "uniq_extra_service_branch_name",
        ["branch_id", "name"],
    )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('businesses', '0005_branch_themes_m2m'),
        ('service_orders', '0002_extraservice_icon'),
    ]

    operations = [
        migrations.RunPython(ensure_service_order_schema, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='serviceorder',
                    options={'ordering': ['-created_at']},
                ),
                migrations.AlterField(
                    model_name='serviceorder',
                    name='status',
                    field=models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('CONFIRMED', 'Confirmed'),
                            ('IN_PROGRESS', 'In progress'),
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        db_index=True,
                        default='PENDING',
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.RunPython(dedupe_extra_services, migrations.RunPython.noop),
        migrations.RunPython(add_extra_service_constraint, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='extraservice',
                    constraint=models.UniqueConstraint(fields=('branch', 'name'), name='uniq_extra_service_branch_name'),
                ),
            ],
        ),
    ]
