# Generated by Django 6.0.2 on 2026-05-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('RECEPTIONIST', 'Receptionist'), ('HOUSEKEEPING', 'Housekeeping'), ('MANAGER', 'Manager'), ('SERVICE', 'Service')], default='RECEPTIONIST', max_length=32),
        ),
    ]
